version: 2
jobs:
  build:
    parallelism: 4
    working_directory: ~/myflix
    docker:
      - image: circleci/ruby:2.3.6-node-browsers
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          PGHOST: localhost
          PGUSER: postgres
      - image: circleci/postgres:9.6.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: myflix_test
      - image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
        environment:
          xpack.security.enabled: false
          transport.host: localhost
    steps:
      - checkout

      - restore_cache:
          key: myflix-app-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: myflix-app-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database setup
          command: bundle exec rake db:create db:schema:load --trace

      - run:
          name: Create the screenshot artifact directory
          command: mkdir -p /tmp/capybara;

      - run: |
          bundle exec rspec -r rspec_junit_formatter \
                            --format RspecJunitFormatter \
                            --out ~/myflix/tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings --timings-type=classname)

      # Save artifacts
      - store_test_results:
          path: ~/myflix/tmp/test-results
      - store_artifacts:
          path: ~/myflix/tmp/test-results
      - store_artifacts:
          path: ~/myflix/tmp/capybara

  deploy_staging:
    machine:
        enabled: true
    working_directory: ~/myflix
    environment:
      HEROKU_APP: "tt-staging-myflix"
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh

      - run:
          command: |
            heroku maintenance:on
            git push --force git@heroku.com:$HEROKU_APP.git $CIRCLE_SHA1:refs/heads/master
            heroku run rake db:migrate
            heroku run rake elasticsearch:index
            heroku maintenance:off

            sleep 5 # sleep for 5 seconds to wait for dynos
            heroku restart

  deploy_production:
    machine:
        enabled: true
    working_directory: ~/myflix
    environment:
      HEROKU_APP: "tt-myflix"
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh

      - run:
          command: |
            heroku maintenance:on
            heroku pg:backups capture
            git push --force git@heroku.com:$HEROKU_APP.git $CIRCLE_SHA1:refs/heads/master
            heroku run rake db:migrate
            heroku run rake elasticsearch:index
            heroku maintenance:off

            sleep 5 # sleep for 5 seconds to wait for dynos
            heroku restart

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_staging:
          requires:
            - build
          filters:
            branches:
              only: staging
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master
